services:
  mntsrv:
    image: ghcr.io/romeniwebdesign/mntsrv:v0.1.0
    container_name: mntsrv
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SCAN_ROOT=${SCAN_ROOT:-/data}
      - PORT=${PORT}
    ports:
      - "7000:7000"
    volumes:
      - ./data:/data
      - ./backend/config:/app/backend/config
      - ./backend/cache:/app/backend/cache
    user: "${UID}:${GID}"
    restart: unless-stopped
